name: 04-using-actions
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: 04-using-actions/reactapp
        steps:
            - name: checkout code
              uses: actions/checkout@v7

            - name: printing folders
              run: ls

            - name: setup node
              uses: actions/setup-node@v6
              with:
                node-version: "24.0.0"
            
            - name: install dependencies
              run: npm ci

            - name: Run Unit tests
              run: npm run test
              