name: 05-02-filter-activity-types

on: 
  pull_request:
    types:
      - closed
      
    branches:
    - main

jobs:
    echo-hello:
        runs-on: ubuntu-latest
        steps:
            - run: echo "run only on main, when PR is closed"

