name: 09-functions

on:
  pull_request:
  push:
  workflow_dispatch: 

jobs:
    github-functions:
        runs-on: ubuntu-latest
        steps:
            - name: print github PR titles
              run: echo "${{ github.event.pull_request.title }}"

            - name: print PR labels
              run:  |
                 cat << EOF
                 ${{ toJson(github.event.pull_request.labels) }}
                 EOF

            - name: Bug step
              if: ${{ !cancelled() && contains(github.event.pull_request.title, 'fix')}}
              run: echo "i am a bug fix"

    status-check-functions:
        runs-on: ubuntu-latest
        steps:
            - name: This step will fail
              run: exit 1

            - name: I will be skipped
              if: ${{ success() }}
              run: echo " I will be run if previous step is successful"

            - name: I will execute if previous step fails
              if: ${{ failure() }}
              run: echo " I will be run if previous step fails"

            - name: i will execute if not cancelled
              if: ${{ !cancelled() }}
              run: echo " I will print always unless the workflow is cancelled"

            - name: i will execute if  cancelled
              if: ${{ cancelled() }}
              run: echo " I will print only if the workflow is cancelled"